import { HistoryItemProps } from "../components/history/historyItem";

export const historyItems: HistoryItemProps[] = [
	{
		title: "Fotovoltáico",
		description: "Instalação de 6 placas fotovoltáicas",
		value: 348.22,
		status: "Negada",
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		title: "Fotovoltáico",
		description: "Instalação de 6 placas fotovoltáicas",
		value: 348.22,
		status: "Em andamento",
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		title: "Fotovoltáico",
		description: "Instalação de 6 placas fotovoltáicas",
		value: 348.22,
		status: "Finalizada",
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		title: "Fotovoltáico",
		description: "Instalação de 6 placas fotovoltáicas",
		value: 348.22,
		status: "Negada",
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		title: "Fotovoltáico",
		description: "Instalação de 6 placas fotovoltáicas",
		value: 348.22,
		status: "Em andamento",
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		title: "Fotovoltáico",
		description: "Instalação de 6 placas fotovoltáicas",
		value: 348.22,
		status: "Finalizada",
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		title: "Fotovoltáico",
		description: "Instalação de 6 placas fotovoltáicas",
		value: 348.22,
		status: "Negada",
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		title: "Fotovoltáico",
		description: "Instalação de 6 placas fotovoltáicas",
		value: 348.22,
		status: "Em andamento",
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		title: "Fotovoltáico",
		description: "Instalação de 6 placas fotovoltáicas",
		value: 348.22,
		status: "Finalizada",
		createdAt: new Date(),
		updatedAt: new Date(),
	},
];
