import { DataTableProps } from "../components/table";

export const tableData: DataTableProps["data"] = [
	{
		address: "Rod. Pref. Luiz Salomão Chamma, 240",
		person: "Pessoa Física",
		code: "faba4daa",
		status: "Finalizado",
		createdAt: "7 dias",
		options: {
			text: "Detalhes",
			route: "/details/faba4daa",
		},
	},
	{
		address: "Av. Paulista, 1578",
		person: "Pessoa Física",
		code: "ab123cd4",
		status: "Em andamento",
		createdAt: "5 dias",
		options: {
			text: "Detalhes",
			route: "/details/ab123cd4",
		},
	},
	{
		address: "Rua das Flores, 45",
		person: "Pessoa Jurídica",
		code: "gh567ij8",
		status: "Negada",
		createdAt: "10 dias",
		options: {
			text: "Detalhes",
			route: "/details/gh567ij8",
		},
	},
	{
		address: "Av. Brasil, 200",
		person: "Pessoa Jurídica",
		code: "kl901mn2",
		status: "Finalizado",
		createdAt: "3 dias",
		options: {
			text: "Detalhes",
			route: "/details/kl901mn2",
		},
	},
	{
		address: "Rua do Comércio, 30",
		person: "Pessoa Jurídica",
		code: "op345qr6",
		status: "Em andamento",
		createdAt: "12 dias",
		options: {
			text: "Detalhes",
			route: "/details/op345qr6",
		},
	},
	{
		address: "Praça da Sé, 1",
		person: "Pessoa Física",
		code: "st789uv0",
		status: "Negada",
		createdAt: "8 dias",
		options: {
			text: "Detalhes",
			route: "/details/st789uv0",
		},
	},
	{
		address: "Av. das Nações Unidas, 300",
		person: "Pessoa Física",
		code: "wx123yz4",
		status: "Finalizado",
		createdAt: "15 dias",
		options: {
			text: "Detalhes",
			route: "/details/wx123yz4",
		},
	},
	{
		address: "Rua Augusta, 1020",
		person: "Pessoa Jurídica",
		code: "ab567cd8",
		status: "Em andamento",
		createdAt: "1 dia",
		options: {
			text: "Detalhes",
			route: "/details/ab567cd8",
		},
	},
	{
		address: "Av. Ibirapuera, 3000",
		person: "Pessoa Física",
		code: "ef901gh2",
		status: "Negada",
		createdAt: "6 dias",
		options: {
			text: "Detalhes",
			route: "/details/ef901gh2",
		},
	},
	{
		address: "Rua do Ouro, 50",
		person: "Pessoa Jurídica",
		code: "ij345kl6",
		status: "Finalizado",
		createdAt: "9 dias",
		options: {
			text: "Detalhes",
			route: "/details/ij345kl6",
		},
	},
	{
		address: "Rua XV de Novembro, 250",
		person: "Pessoa Física",
		code: "mn789op0",
		status: "Em andamento",
		createdAt: "4 dias",
		options: {
			text: "Detalhes",
			route: "/details/mn789op0",
		},
	},
	{
		address: "Av. Brigadeiro Faria Lima, 100",
		person: "Pessoa Jurídica",
		code: "qr123st4",
		status: "Negada",
		createdAt: "11 dias",
		options: {
			text: "Detalhes",
			route: "/details/qr123st4",
		},
	},
	{
		address: "Rua São João, 400",
		person: "Pessoa Física",
		code: "uv567wx8",
		status: "Finalizado",
		createdAt: "2 dias",
		options: {
			text: "Detalhes",
			route: "/details/uv567wx8",
		},
	},
	{
		address: "Av. República do Líbano, 700",
		person: "Pessoa Jurídica",
		code: "yz901ab2",
		status: "Em andamento",
		createdAt: "13 dias",
		options: {
			text: "Detalhes",
			route: "/details/yz901ab2",
		},
	},
	{
		address: "Rua das Palmeiras, 55",
		person: "Pessoa Física",
		code: "cd345ef6",
		status: "Negada",
		createdAt: "14 dias",
		options: {
			text: "Detalhes",
			route: "/details/cd345ef6",
		},
	},
	{
		address: "Av. Santo Amaro, 800",
		person: "Pessoa Jurídica",
		code: "gh789ij0",
		status: "Finalizado",
		createdAt: "16 dias",
		options: {
			text: "Detalhes",
			route: "/details/gh789ij0",
		},
	},
	{
		address: "Rua Vergueiro, 500",
		person: "Pessoa Física",
		code: "kl123mn4",
		status: "Em andamento",
		createdAt: "17 dias",
		options: {
			text: "Detalhes",
			route: "/details/kl123mn4",
		},
	},
	{
		address: "Av. Rebouças, 600",
		person: "Pessoa Jurídica",
		code: "op567qr8",
		status: "Negada",
		createdAt: "18 dias",
		options: {
			text: "Detalhes",
			route: "/details/op567qr8",
		},
	},
	{
		address: "Rua dos Andradas, 100",
		person: "Pessoa Física",
		code: "st901uv2",
		status: "Finalizado",
		createdAt: "19 dias",
		options: {
			text: "Detalhes",
			route: "/details/st901uv2",
		},
	},
	{
		address: "Av. Sete de Setembro, 1200",
		person: "Pessoa Jurídica",
		code: "wx345yz6",
		status: "Em andamento",
		createdAt: "20 dias",
		options: {
			text: "Detalhes",
			route: "/details/wx345yz6",
		},
	},
	{
		address: "Rua Barão de Itapetininga, 70",
		person: "Pessoa Física",
		code: "ab123cd4",
		status: "Negada",
		createdAt: "21 dias",
		options: {
			text: "Detalhes",
			route: "/details/ab123cd4",
		},
	},
	{
		address: "Av. dos Bandeirantes, 900",
		person: "Pessoa Jurídica",
		code: "ef567gh8",
		status: "Finalizado",
		createdAt: "22 dias",
		options: {
			text: "Detalhes",
			route: "/details/ef567gh8",
		},
	},
	{
		address: "Rua Domingos de Morais, 110",
		person: "Pessoa Física",
		code: "ij901kl2",
		status: "Em andamento",
		createdAt: "23 dias",
		options: {
			text: "Detalhes",
			route: "/details/ij901kl2",
		},
	},
	{
		address: "Av. Jabaquara, 1500",
		person: "Pessoa Jurídica",
		code: "mn345op6",
		status: "Negada",
		createdAt: "24 dias",
		options: {
			text: "Detalhes",
			route: "/details/mn345op6",
		},
	},
	{
		address: "Rua Teodoro Sampaio, 80",
		person: "Pessoa Física",
		code: "qr789st0",
		status: "Finalizado",
		createdAt: "25 dias",
		options: {
			text: "Detalhes",
			route: "/details/qr789st0",
		},
	},
	{
		address: "Av. Professor Luiz Ignácio de Anhaia Mello, 1000",
		person: "Pessoa Jurídica",
		code: "uv123wx4",
		status: "Em andamento",
		createdAt: "26 dias",
		options: {
			text: "Detalhes",
			route: "/details/uv123wx4",
		},
	},
	{
		address: "Rua Clélia, 150",
		person: "Pessoa Física",
		code: "yz567ab8",
		status: "Negada",
		createdAt: "27 dias",
		options: {
			text: "Detalhes",
			route: "/details/yz567ab8",
		},
	},
	{
		address: "Av. Vereador José Diniz, 1100",
		person: "Pessoa Jurídica",
		code: "cd901ef2",
		status: "Finalizado",
		createdAt: "28 dias",
		options: {
			text: "Detalhes",
			route: "/details/cd901ef2",
		},
	},
	{
		address: "Rua Maria Antônia, 90",
		person: "Pessoa Física",
		code: "gh345ij6",
		status: "Em andamento",
		createdAt: "29 dias",
		options: {
			text: "Detalhes",
			route: "/details/gh345ij6",
		},
	},
	{
		address: "Av. Indianópolis, 1200",
		person: "Pessoa Jurídica",
		code: "kl789mn0",
		status: "Negada",
		createdAt: "30 dias",
		options: {
			text: "Detalhes",
			route: "/details/kl789mn0",
		},
	},
];
