import { Technician } from "../models/technician";

export const technicians: Technician[] = [
	{
		_id: "1",
		name: "Alice Johnson",
		email: "alice.johnson@example.com",
		specialty: "Network Administration",
	},
	{
		_id: "2",
		name: "Bob Smith",
		email: "bob.smith@example.com",
		specialty: "Cybersecurity",
	},
	{
		_id: "3",
		name: "Carol White",
		email: "carol.white@example.com",
		specialty: "Cloud Computing",
	},
	{
		_id: "4",
		name: "David Brown",
		email: "david.brown@example.com",
		specialty: "Database Management",
	},
	{
		_id: "5",
		name: "Eve Davis",
		email: "eve.davis@example.com",
		specialty: "Software Development",
	},
	{
		_id: "6",
		name: "Frank Miller",
		email: "frank.miller@example.com",
		specialty: "Web Development",
	},
	{
		_id: "7",
		name: "Grace Wilson",
		email: "grace.wilson@example.com",
		specialty: "Mobile Development",
	},
	{
		_id: "8",
		name: "Hank Moore",
		email: "hank.moore@example.com",
		specialty: "Data Science",
	},
	{
		_id: "9",
		name: "Ivy Taylor",
		email: "ivy.taylor@example.com",
		specialty: "Artificial Intelligence",
	},
	{
		_id: "10",
		name: "Jack Anderson",
		email: "jack.anderson@example.com",
		specialty: "Machine Learning",
	},
	{
		_id: "11",
		name: "Karen Thomas",
		email: "karen.thomas@example.com",
		specialty: "DevOps",
	},
	{
		_id: "12",
		name: "Leo Jackson",
		email: "leo.jackson@example.com",
		specialty: "System Administration",
	},
	{
		_id: "13",
		name: "Mona Lee",
		email: "mona.lee@example.com",
		specialty: "Network Security",
	},
	{
		_id: "14",
		name: "Nina Harris",
		email: "nina.harris@example.com",
		specialty: "Big Data",
	},
	{
		_id: "15",
		name: "Oscar Martin",
		email: "oscar.martin@example.com",
		specialty: "Robotics",
	},
	{
		_id: "16",
		name: "Paula Clark",
		email: "paula.clark@example.com",
		specialty: "IoT",
	},
	{
		_id: "17",
		name: "Quincy Lewis",
		email: "quincy.lewis@example.com",
		specialty: "Embedded Systems",
	},
	{
		_id: "18",
		name: "Rachel Walker",
		email: "rachel.walker@example.com",
		specialty: "Blockchain",
	},
	{
		_id: "19",
		name: "Steve Hall",
		email: "steve.hall@example.com",
		specialty: "IT Support",
	},
	{
		_id: "20",
		name: "Tina Young",
		email: "tina.young@example.com",
		specialty: "Quality Assurance",
	},
	{
		_id: "21",
		name: "Umar King",
		email: "umar.king@example.com",
		specialty: "Technical Writing",
	},
	{
		_id: "22",
		name: "Vera Wright",
		email: "vera.wright@example.com",
		specialty: "Computer Vision",
	},
	{
		_id: "23",
		name: "Walter Scott",
		email: "walter.scott@example.com",
		specialty: "Augmented Reality",
	},
	{
		_id: "24",
		name: "Xena Green",
		email: "xena.green@example.com",
		specialty: "Virtual Reality",
	},
	{
		_id: "25",
		name: "Yara Adams",
		email: "yara.adams@example.com",
		specialty: "Game Development",
	},
	{
		_id: "26",
		name: "Zane Baker",
		email: "zane.baker@example.com",
		specialty: "Telecommunications",
	},
	{
		_id: "27",
		name: "Ava Carter",
		email: "ava.carter@example.com",
		specialty: "Hardware Engineering",
	},
	{
		_id: "28",
		name: "Brian Collins",
		email: "brian.collins@example.com",
		specialty: "Software Engineering",
	},
	{
		_id: "29",
		name: "Cathy Cooper",
		email: "cathy.cooper@example.com",
		specialty: "Information Security",
	},
	{
		_id: "30",
		name: "Doug Edwards",
		email: "doug.edwards@example.com",
		specialty: "Penetration Testing",
	},
	{
		_id: "31",
		name: "Ella Evans",
		email: "ella.evans@example.com",
		specialty: "Digital Forensics",
	},
	{
		_id: "32",
		name: "Fred Foster",
		email: "fred.foster@example.com",
		specialty: "Systems Analysis",
	},
	{
		_id: "33",
		name: "Gina Gonzalez",
		email: "gina.gonzalez@example.com",
		specialty: "IT Project Management",
	},
	{
		_id: "34",
		name: "Henry Hill",
		email: "henry.hill@example.com",
		specialty: "Cloud Architecture",
	},
	{
		_id: "35",
		name: "Iris Hughes",
		email: "iris.hughes@example.com",
		specialty: "Data Engineering",
	},
	{
		_id: "36",
		name: "Jake Jackson",
		email: "jake.jackson@example.com",
		specialty: "Full Stack Development",
	},
	{
		_id: "37",
		name: "Kelly Kelly",
		email: "kelly.kelly@example.com",
		specialty: "UI/UX Design",
	},
	{
		_id: "38",
		name: "Liam Lee",
		email: "liam.lee@example.com",
		specialty: "Technical Support",
	},
	{
		_id: "39",
		name: "Maya Martinez",
		email: "maya.martinez@example.com",
		specialty: "Business Analysis",
	},
	{
		_id: "40",
		name: "Nick Nelson",
		email: "nick.nelson@example.com",
		specialty: "Network Engineering",
	},
	{
		_id: "41",
		name: "Olivia Ortiz",
		email: "olivia.ortiz@example.com",
		specialty: "Database Architecture",
	},
	{
		_id: "42",
		name: "Paul Parker",
		email: "paul.parker@example.com",
		specialty: "IT Consulting",
	},
	{
		_id: "43",
		name: "Quinn Quinn",
		email: "quinn.quinn@example.com",
		specialty: "Agile Coaching",
	},
	{
		_id: "44",
		name: "Rose Reed",
		email: "rose.reed@example.com",
		specialty: "SCRUM Master",
	},
	{
		_id: "45",
		name: "Sam Sanders",
		email: "sam.sanders@example.com",
		specialty: "IT Training",
	},
	{
		_id: "46",
		name: "Tara Turner",
		email: "tara.turner@example.com",
		specialty: "Tech Support",
	},
	{
		_id: "47",
		name: "Ursula Underwood",
		email: "ursula.underwood@example.com",
		specialty: "Network Design",
	},
	{
		_id: "48",
		name: "Victor Vaughn",
		email: "victor.vaughn@example.com",
		specialty: "Enterprise Architecture",
	},
	{
		_id: "49",
		name: "Wendy Watson",
		email: "wendy.watson@example.com",
		specialty: "System Integration",
	},
];
